fix: checks bytes32
defi-wonderland/prophet-modules pull request #44
Opened 2024-07-08 21:51 UTC by ashitakah

# 🤖 Linear

Closes TOB-WOND-6

2024-07-10 03:14 UTC, 0xJabberwock commented on solidity/contracts/modules/dispute/RootVerificationModule.sol
> +    if (_response.response.length != 32) revert RootVerificationModule_InvalidResponseLength();
Thinking out loud, I guess `IOracle.Response.response` shouldn't be set to a `bytes32` since other use cases would be limited.

2024-07-13 00:21 UTC, ashitakah commented on solidity/contracts/modules/dispute/RootVerificationModule.sol
> +    if (_response.response.length != 32) revert RootVerificationModule_InvalidResponseLength();
@0xJabberwock @0xShaito TBH, I thought the same as you that it's OK to check for length 32 but I don't know if we are missing things for other processes that occur.

2024-07-13 00:24 UTC, ashitakah commented on solidity/test/unit/modules/dispute/RootVerificationModule.t.sol
> +    vm.assume(_length != 32);
EvmError: MemoryLimitOOG with uint256

2024-07-16 00:27 UTC, 0xShaito commented on solidity/contracts/modules/dispute/RootVerificationModule.sol
> +    if (_response.response.length != 32) revert RootVerificationModule_InvalidResponseLength();
Even though I agree that it would be cool to change the response type (for size). Not related to this task particularly. @gas1cent do you have any input into changing the type? Why did we end up using bytes32?

2024-07-16 00:27 UTC, 0xShaito commented on solidity/contracts/modules/dispute/RootVerificationModule.sol
> +    if (_response.response.length != 32) revert RootVerificationModule_InvalidResponseLength();
I guess because of the hashing

2024-07-16 00:30 UTC, 0xShaito requested changes

2024-07-16 00:30 UTC, 0xShaito commented on solidity/contracts/modules/dispute/RootVerificationModule.sol
> +    if (_response.response.length != 32) revert RootVerificationModule_InvalidResponseLength();
@0xJabberwock this only affects the RootVerificationModule. Please also add this to the `validateParameters` function

2024-07-16 06:08 UTC, 0xJabberwock approved these changes

2024-07-16 16:24 UTC, merged