fix: adding escalated status check
defi-wonderland/prophet-modules pull request #46
Opened 2024-07-08 22:27 UTC by ashitakah

# 🤖 Linear

Closes GRT-7

2024-07-09 13:26 UTC, 0xShaito requested changes

2024-07-09 13:26 UTC, 0xShaito commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +    if (
Add tests so that the error that was present before is not present anymore

2024-07-09 13:26 UTC, 0xShaito commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +        && ORACLE.disputeStatus(_disputeId) != IOracle.DisputeStatus.Escalated
The finding only says to check against `IOracle.DisputeStatus.Escalated`. Does it also need to keep None? What is that case?

2024-07-13 00:44 UTC, ashitakah commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +    if (
👍

2024-07-13 00:44 UTC, ashitakah commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +        && ORACLE.disputeStatus(_disputeId) != IOracle.DisputeStatus.Escalated
Yep we should left the None also, is the other case which the dispute can be voted

2024-07-16 00:21 UTC, 0xShaito submitted a review, later dismissed

2024-07-16 06:36 UTC, 0xJabberwock requested changes

2024-07-16 06:36 UTC, 0xJabberwock commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +        && ORACLE.disputeStatus(_disputeId) != IOracle.DisputeStatus.Escalated
The audit says that it should be just `ORACLE.disputeStatus(_disputeId) != IOracle.DisputeStatus.Escalated`.

2024-07-16 06:36 UTC, 0xJabberwock commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
>        revert PrivateERC20ResolutionModule_AlreadyResolved();
Tests for `resolveDispute()` are lacking.

2024-07-17 18:37 UTC, ashitakah commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
>        revert PrivateERC20ResolutionModule_AlreadyResolved();
👍

2024-07-17 19:52 UTC, ashitakah commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +        && ORACLE.disputeStatus(_disputeId) != IOracle.DisputeStatus.Escalated
I think the same as you, however Im not sure if in some case we need to commit a vote or resolve without be escalated

2024-07-17 20:10 UTC, gas1cent commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +        && ORACLE.disputeStatus(_disputeId) != IOracle.DisputeStatus.Escalated
@0xShaito @0xJabberwock the `None` status means the dispute has not started yet.

There are 2 somewhat realistic scenarios that could lead to a dispute having the `None` in this function:
1. The ID is incorrect, in which case `ORACLE.createdAt(_disputeId) == 0` effectively duplicates this check.
2. The dispute was created in a messed up module that somehow called the `updateDisputeStatus` function of the oracle and set an invalid status.

The second point is a bit concerning but the off-chain logic should catch that, so I would remove the `None` check.

2024-07-18 05:03 UTC, 0xJabberwock approved these changes

2024-07-18 14:18 UTC, 0xShaito approved these changes

2024-07-18 14:18 UTC, merged