fix: not pledged
defi-wonderland/prophet-modules pull request #47
Opened 2024-07-08 22:55 UTC by ashitakah

# 🤖 Linear

Closes GRT-8

The problem is that according to the report when the dispute is in non-resolution, everyone can access a pledge. The issue is that it doesn't check if that user made a previous pledge and anyone could subtract it in that state. 

I have opted to create a mapping that both this in no resolution or if when you make a pledge you put it in true and if not in false, I do not know if it solves the problem 100%. 

REVIEW!

2024-07-09 20:00 UTC, 0xShaito requested changes

2024-07-09 20:00 UTC, 0xShaito commented on solidity/contracts/extensions/BondEscalationAccounting.sol
> +    pledgerHasPledged[_disputeId][_pledger] = true;
Can't the same pledger pledge multiple times? This would kill that right?

2024-07-13 00:15 UTC, ashitakah commented on solidity/contracts/extensions/BondEscalationAccounting.sol
> +    pledgerHasPledged[_disputeId][_pledger] = true;
Yep, but as far I know if the resolution is non, the user can claim their pledge 1 time, so with that will be solve I guess.

2024-07-16 00:17 UTC, 0xShaito commented on solidity/contracts/extensions/BondEscalationAccounting.sol
> +    pledgerHasPledged[_disputeId][_pledger] = true;
No because they will only be able to claim 1 pledge. Losing the rest of the money

2024-07-16 00:20 UTC, 0xShaito commented on solidity/contracts/extensions/BondEscalationAccounting.sol
> +    pledgerHasPledged[_disputeId][_pledger] = true;
Missed the check for amount of pledges. You are right! Tests are failing though

2024-07-16 00:20 UTC, 0xShaito commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +    bondEscalationAccounting.forTest_setPledgerHasPledged(_disputeId, pledger, true);
Do we have a test for someone who pledged multiple times?

2024-07-22 14:54 UTC, 0xShaito requested changes

2024-07-22 14:54 UTC, 0xShaito commented on solidity/test/integration/BondEscalation.t.sol
> +    // _bondEscalationAccounting.claimEscalationReward(_disputeId, requester);
Why comment?

2024-07-22 14:54 UTC, 0xShaito commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +    bondEscalationAccounting.forTest_setPledge(_disputeId, token, _amount * _pledges * 2);
Can we have a different number of pledges for and against so we are sure we are adding both numbers correctly?

2024-07-24 02:03 UTC, ashitakah commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +    bondEscalationAccounting.forTest_setPledge(_disputeId, token, _amount * _pledges * 2);
👍

2024-07-24 02:03 UTC, ashitakah commented on solidity/test/integration/BondEscalation.t.sol
> +    // _bondEscalationAccounting.claimEscalationReward(_disputeId, requester);
mistake

2024-07-24 02:37 UTC, 0xJabberwock approved these changes

2024-07-24 17:29 UTC, 0xShaito approved these changes

2024-07-24 17:30 UTC, merged