fix: unlock without pledge
defi-wonderland/prophet-modules pull request #48
Opened 2024-07-09 01:53 UTC by ashitakah

# 🤖 Linear

Closes GRT-9

2024-07-09 13:29 UTC, 0xShaito requested changes

2024-07-09 13:29 UTC, 0xShaito commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +        if (_pledgesAgainstDispute > 0 || _pledgesForDispute > 0) {
This should be fixed directly in the bondEscalationAccounting so we don't leave a hole in case they don't use this particular module. Also add tests to check that the error is fixed and compare.

2024-07-12 22:50 UTC, ashitakah commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +        if (_pledgesAgainstDispute > 0 || _pledgesForDispute > 0) {
I don't understand what you mean by resolving it in bondEscalationAccounting. In this contract it already contemplates that it can be either the number of disputed or the other number. On the contrary in this module it does not.

2024-07-16 00:16 UTC, 0xShaito submitted a review, later dismissed

2024-07-19 17:49 UTC, 0xJabberwock requested changes
Tests are lacking for the change.

2024-07-22 14:41 UTC, 0xShaito approved these changes

2024-07-22 18:53 UTC, 0xJabberwock requested changes

2024-07-22 18:53 UTC, 0xJabberwock commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +        if (_pledgesAgainstDispute > 0 || _pledgesForDispute > 0) {
I found out that both cases were already being considered in the test suite, particularly in `test_shouldChangeBondEscalationStatusAndCallPayPledgersWon` and `test_shouldChangeBondEscalationStatusAndCallPayPledgersLost`, but shallowly.

```solidity
// Mock and expect IBondEscalationAccounting.onSettleBondEscalation to be called
_mockAndExpect(
  address(_params.accountingExtension),
  abi.encodeCall(
    IBondEscalationAccounting.onSettleBondEscalation,
    (_requestId, _disputeId, _params.bondToken, _params.bondSize << 1, _numForPledgers)
  ),
  abi.encode()
);
```

```solidity
// Mock and expect IBondEscalationAccounting.onSettleBondEscalation to be called
vm.mockCall(
  address(_params.accountingExtension),
  abi.encodeCall(
    IBondEscalationAccounting.onSettleBondEscalation,
    (_requestId, _disputeId, _params.bondToken, _params.bondSize << 1, _numAgainstPledgers)
  ),
  abi.encode(true)
);
```

In the second test case, changing `vm.mockCall()` for `_mockAndExpect()` would suffice, although having `_numForPledgers` and `_numAgainstPledgers` hardcoded to be the same number isn't robust at all.

2024-07-22 18:53 UTC, 0xJabberwock commented on solidity/test/unit/modules/dispute/BondEscalationModule.t.sol
> +  function test_callPayIfNormalDisputeWonPledgesForDispute(
Having said the previous, this test case could be deleted as it is less complete (it doesn't expect a call to `onSettleBondEscalation()`).

2024-07-24 02:06 UTC, ashitakah commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +        if (_pledgesAgainstDispute > 0 || _pledgesForDispute > 0) {
I think the same as you, but if I am right @0xShaito , he told me that the testing team was going to review and improve all the testing since they are very weak and we have seen it in the audit. I don't know if we should wait for this to happen. @0xJabberwock

2024-07-24 02:07 UTC, ashitakah commented on solidity/test/unit/modules/dispute/BondEscalationModule.t.sol
> +  function test_callPayIfNormalDisputeWonPledgesForDispute(
Same comment as before

2024-07-24 02:33 UTC, 0xJabberwock commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +        if (_pledgesAgainstDispute > 0 || _pledgesForDispute > 0) {
I would try to be as sensible as I could with the test cases reached as from the audit fixes, even considering that a further test suite review by the testing team might be coming.

2024-07-26 07:27 UTC, 0xJabberwock approved these changes

2024-07-26 12:02 UTC, 0xShaito approved these changes

2024-07-26 12:03 UTC, merged