fix: checks address proposer
defi-wonderland/prophet-modules pull request #49
Opened 2024-07-09 02:19 UTC by ashitakah

# 🤖 Linear

Closes GRT-12

2024-07-09 13:31 UTC, 0xShaito requested changes

2024-07-11 01:20 UTC, ashitakah commented on solidity/contracts/modules/dispute/BondedDisputeModule.sol
> +      if (_dispute.proposer != _response.proposer) revert BondedDisputeModule_OnlyResponseProposer();
I don't see why call it self because this happens when you try to change the address it receives but oka.

2024-07-11 07:30 UTC, 0xJabberwock commented on solidity/contracts/modules/dispute/BondedDisputeModule.sol
> +      if (_dispute.proposer != _response.proposer) revert BondedDisputeModule_OnlyResponseProposer();
Indeed, what matters is that the `proposer` in the `IOracle.Response` struct is expected to be equal to the same in the `IOracle.Dispute` struct, despite being arbitrarily inputted by the caller. The fact that someone might dispute himself is not the focus of the issue and is not affected by the reversion above.

2024-07-11 07:30 UTC, 0xJabberwock reviewed
Shouldn't this issue be validated in `Oracle.disputeResponse()`?

2024-07-12 20:13 UTC, 0xShaito commented
> Shouldn't this issue be validated in `Oracle.disputeResponse()`?

I agree @0xJabberwock. I prefer if we do it in the oracle!

2024-07-12 22:36 UTC, closed without merging