fix: request id validation
defi-wonderland/prophet-modules pull request #51
Opened 2024-07-19 06:17 UTC by 0xJabberwock

# 🤖 Linear

Closes GRT-3

2024-07-19 06:33 UTC, 0xJabberwock reviewed
`TOB-WOND-4` explicitly mentions that the dispute's `requestId` validation issue could be found within `BondEscalationResolutionModule`, `BondEscalationModule`, `PrivateERC20ResolutionModule` and `ERC20ResolutionModule`. However, I was able to detect the lack of the same recommended check around many other modules. Should this be a concern?

Besides, other similar validations are also extendedly absent, such as comparing with the response's `requestId` or the dispute's `responseId`. Again, should this be a concern?

2024-07-19 06:33 UTC, 0xJabberwock commented on solidity/interfaces/modules/resolution/IERC20ResolutionModule.sol
>    error ERC20ResolutionModule_OnlyDisputeModule();
This custom error is not being used anywhere. 🙄

2024-07-19 13:05 UTC, 0xShaito submitted a review, later dismissed

2024-07-20 07:26 UTC, 0xJabberwock commented
> `TOB-WOND-4` explicitly mentions that the dispute's `requestId` validation issue could be found within `BondEscalationResolutionModule`, `BondEscalationModule`, `PrivateERC20ResolutionModule` and `ERC20ResolutionModule`. However, I was able to detect the lack of the same recommended check around many other modules. Should this be a concern?

It should not. This is due to every function lacking `requestId` checks being `onlyOracle`, contract where the appropriate validations are being performed.

> Besides, other similar validations are also extendedly absent, such as comparing with the response's `requestId` or the dispute's `responseId`. Again, should this be a concern?

It should not be it outside of the warned modules, for the same reason; within the warned modules, there was one case where a `responseId` validation was due.

2024-07-24 17:51 UTC, 0xShaito submitted a review, later dismissed

2024-07-26 00:48 UTC, ashitakah requested changes

2024-07-26 00:48 UTC, ashitakah commented on solidity/test/unit/modules/resolution/BondEscalationResolutionModule.t.sol
>    function test_reverts(
Could you remane to specify the test function?

2024-07-26 00:48 UTC, ashitakah commented on solidity/test/unit/modules/resolution/BondEscalationResolutionModule.t.sol
>    function test_reverts(
same here

2024-07-26 12:01 UTC, 0xShaito approved these changes

2024-07-26 17:45 UTC, ashitakah approved these changes

2024-07-26 17:49 UTC, merged