feat: not eoa
defi-wonderland/prophet-modules pull request #52
Opened 2024-07-19 17:13 UTC by ashitakah

# 🤖 Linear

Closes GRT-21

2024-07-22 18:06 UTC, 0xJabberwock requested changes
The audit mentions that the issue is also present at least in `CircuitResolver.sol`.

2024-07-22 18:06 UTC, 0xJabberwock commented on solidity/contracts/modules/finality/CallbackModule.sol
> +    _valid = address(_params.target) != address(0) && _params.data.length != 0 && _targetHasBytecode(_params.target);
Can `address(0)` ever have bytecode? If not, the first comparison could be avoided.

2024-07-22 18:06 UTC, 0xJabberwock commented on solidity/contracts/modules/finality/CallbackModule.sol
>      emit RequestFinalized(_response.requestId, _response, _finalizer);
How come `validateParameters()` gets called during this context?

2024-07-22 21:33 UTC, 0xShaito commented on solidity/contracts/modules/finality/CallbackModule.sol
>      emit RequestFinalized(_response.requestId, _response, _finalizer);
It's an off-chain validation

2024-07-24 02:24 UTC, 0xJabberwock approved these changes

2024-07-24 17:31 UTC, 0xShaito approved these changes

2024-07-24 17:31 UTC, merged