fix: wond-15
defi-wonderland/prophet-modules pull request #54
Opened 2024-07-26 17:31 UTC by 0xShaito

# 🤖 Linear

Closes OPO-XXX

2024-07-27 19:38 UTC, 0xJabberwock requested changes
What if an attacker creates a malicious request that features victim-approved response and dispute modules? 🤔

2024-07-27 19:38 UTC, 0xJabberwock commented on solidity/contracts/extensions/AccountingExtension.sol
> +    bool _senderApproved = _bonder == _sender || _approvals[_bonder].contains(_sender);
Should the `_bonder == _sender` check be performed in the `AccountingExtension`? It would also be viable within the `BondedResponseModule`, where if it resolves to `true` the `bond()` signature without the `_sender` could be called, enhancing function discrimination.

2024-07-27 19:38 UTC, 0xJabberwock commented on solidity/contracts/extensions/AccountingExtension.sol
>      }
Unit tests for this change are lacking.

2024-07-27 19:38 UTC, 0xJabberwock commented on solidity/test/integration/ResponseProposal.t.sol
> +    bytes32 _requestIdApprovedDisputeModule = oracle.createRequest(mockRequest, _ipfsHash);
Looking at the comment, wouldn't it be a `new request` rather than a `new proposal`?

2024-07-27 19:38 UTC, 0xJabberwock commented on solidity/test/integration/ResponseProposal.t.sol
> +    vm.startPrank(_approvedDisputeModule);
`stopPrank()` could be erased. Apparently, `startPrank()` and `changePrank()` have become more interchangeable.

2024-07-27 19:38 UTC, 0xJabberwock commented on solidity/test/integration/ResponseProposal.t.sol
> +    _accountingExtension.approveModule(_approvedDisputeModule);
Prank the `proposer` and test will pass.

2024-07-27 19:38 UTC, 0xJabberwock commented on solidity/test/integration/RootVerification.t.sol
>      oracle.disputeResponse(mockRequest, mockResponse, mockDispute);
By applying comment, the `disputer` wouldn't need to approve both response and dispute modules, but the first one.

2024-07-29 14:45 UTC, 0xShaito commented on solidity/test/integration/ResponseProposal.t.sol
> +    bytes32 _requestIdApprovedDisputeModule = oracle.createRequest(mockRequest, _ipfsHash);
Yes!

2024-07-29 15:14 UTC, 0xShaito commented on solidity/test/integration/ResponseProposal.t.sol
> +    vm.startPrank(_approvedDisputeModule);
👍

2024-07-29 15:15 UTC, 0xShaito commented on solidity/test/integration/ResponseProposal.t.sol
> +    _accountingExtension.approveModule(_approvedDisputeModule);
👍

2024-07-29 17:27 UTC, 0xShaito commented
> What if an attacker creates a malicious request that features victim-approved response and dispute modules? 🤔 

@0xJabberwock in this case do you see an attack in any way? Or is the attacked approving the malicious contracts?

2024-07-29 19:26 UTC, 0xJabberwock commented
> > What if an attacker creates a malicious request that features victim-approved response and dispute modules? 🤔
> 
> @0xJabberwock in this case do you see an attack in any way? Or is the attacked approving the malicious contracts?

I think that low-level calls from allowed and approved modules might allow enough attack surface for this issue to keep happening. Coincidentally, this concern brings `TOB-WOND-11` in.

2024-07-30 14:16 UTC, ashitakah submitted a review, later dismissed
left some comments, PR looks good!

2024-07-30 23:00 UTC, 0xJabberwock requested changes

2024-07-30 23:00 UTC, 0xJabberwock commented on solidity/test/unit/extensions/AccountingExtension.t.sol
> +    extension.approveModule(_module);
Why this change here? It shouldn't be needed for the test to pass since it calls the `bond()` function with the single `_approvals` check.

2024-07-30 23:00 UTC, 0xJabberwock commented on solidity/test/unit/modules/response/BondedResponseModule.t.sol
> +      abi.encodeWithSignature('bond(address,bytes32,address,uint256)', _proposer, _requestId, _token, _bondSize),
The fuzzed `_sender` is no longer used here as the `bond()` function being called is the one without it.

2024-07-30 23:00 UTC, 0xJabberwock commented on solidity/test/unit/extensions/AccountingExtension.t.sol
> +  function test_withCaller_revertIfInsufficientAllowance_onlySender(
The name of the test cases expecting the reversion of `AccountingExtension_NotAllowed` should be updated.

2024-07-30 23:49 UTC, 0xShaito commented on solidity/test/unit/extensions/AccountingExtension.t.sol
> +    extension.approveModule(_module);
100% bad copy paste from the sender

2024-07-30 23:50 UTC, 0xShaito commented on solidity/test/unit/extensions/AccountingExtension.t.sol
> +  function test_withCaller_revertIfInsufficientAllowance_onlySender(
Good catch!

2024-07-30 23:50 UTC, 0xShaito commented on solidity/test/unit/modules/response/BondedResponseModule.t.sol
> +      abi.encodeWithSignature('bond(address,bytes32,address,uint256)', _proposer, _requestId, _token, _bondSize),
ty!

2024-07-31 00:05 UTC, 0xJabberwock approved these changes

2024-07-31 01:19 UTC, ashitakah approved these changes

2024-07-31 19:33 UTC, merged