Fix/wond 5
defi-wonderland/prophet-modules pull request #55
Opened 2024-07-26 22:03 UTC by 0xShaito

# 🤖 Linear

Closes OPO-XXX

2024-08-02 18:26 UTC, 0xng commented on solidity/contracts/extensions/BondEscalationAccounting.sol
> +    if (ORACLE.disputeCreatedAt(_disputeId) == 0) revert BondEscalationAccounting_InvalidDispute();
i believe this is already checked on the `_validateDispute` function

2024-08-02 20:07 UTC, 0xShaito commented on solidity/contracts/extensions/BondEscalationAccounting.sol
> +    if (ORACLE.disputeCreatedAt(_disputeId) == 0) revert BondEscalationAccounting_InvalidDispute();
Yes! removed!

2024-08-02 20:32 UTC, 0xng approved these changes

2024-08-02 23:57 UTC, ashitakah reviewed
Just a few comments, looks solved it to me.

2024-08-02 23:57 UTC, ashitakah commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> -    if (ORACLE.disputeCreatedAt(_disputeId) == 0) revert PrivateERC20ResolutionModule_NonExistentDispute();
Why this check is deleted?

2024-08-02 23:57 UTC, ashitakah commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +    (IOracle.Response memory _response, IOracle.Dispute memory _dispute) = _getRequestAndDispute();
linter

2024-08-03 01:15 UTC, 0xShaito commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> -    if (ORACLE.disputeCreatedAt(_disputeId) == 0) revert PrivateERC20ResolutionModule_NonExistentDispute();
Because it's done in the validateDispute

2024-08-05 07:11 UTC, 0xJabberwock requested changes

2024-08-05 07:11 UTC, 0xJabberwock commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> -    if (ORACLE.disputeCreatedAt(_disputeId) == 0) revert PrivateERC20ResolutionModule_NonExistentDispute();
In consequence, `PrivateERC20ResolutionModule_NonExistentDispute` error could be removed from `IPrivateERC20ResolutionModule`.

2024-08-05 11:37 UTC, gas1cent commented on solidity/contracts/extensions/AccountingExtension.sol
> +contract AccountingExtension is Validator, IAccountingExtension {
Such a great idea to extract the validation logic into a contract.

2024-08-05 15:35 UTC, 0xShaito commented on solidity/contracts/extensions/AccountingExtension.sol
This particular exploit does not affect the accounting extension as it does not depend on disputes

2024-08-05 16:54 UTC, 0xJabberwock approved these changes

2024-08-05 19:18 UTC, ashitakah approved these changes

2024-08-05 19:30 UTC, merged