fix: low-level calls
defi-wonderland/prophet-modules pull request #56
Opened 2024-08-02 06:45 UTC by 0xJabberwock

# 🤖 Linear

Closes GRT-10

2024-08-02 12:03 UTC, 0xShaito requested changes

2024-08-02 12:03 UTC, 0xShaito commented on solidity/contracts/modules/dispute/CircuitResolverModule.sol
> +    try IProphetCallback(_params.verifier).prophetCallback(_params.callData) returns (bytes memory _correctResponse) {
Can we change this one in particular to something different? `prophetVerify`? As it's not a callback per se

2024-08-03 00:10 UTC, ashitakah commented on solidity/contracts/modules/dispute/CircuitResolverModule.sol
> +      _status = _response.response.length != _correctResponse.length
I guess that the response is not gonna be never greater than 32 bytes, because is so, maybe we lose some data in the response and we can have some collisions

2024-08-05 17:56 UTC, 0xJabberwock commented on solidity/contracts/modules/dispute/CircuitResolverModule.sol
> +      _status = _response.response.length != _correctResponse.length
Both `_response.response` and `_correctResponse` are `bytes`, so they may be greater than `bytes32`.

2024-08-05 18:51 UTC, 0xJabberwock commented on solidity/contracts/modules/dispute/CircuitResolverModule.sol
> +    try IProphetCallback(_params.verifier).prophetCallback(_params.callData) returns (bytes memory _correctResponse) {
I'd say it might be understood as a callback because it is a function previously defined by the requester to be called by another function, but it is certain that it doesn't necessarily represent a return to the prior execution flow.

2024-08-05 18:53 UTC, 0xShaito approved these changes

2024-08-05 19:17 UTC, ashitakah approved these changes

2024-08-05 19:29 UTC, merged