feat: add access control for authorized callers
defi-wonderland/prophet-modules pull request #62
Opened 2024-09-19 13:52 UTC by xorsal

# 🤖 Linear

Closes OPO-XXX

2024-09-19 15:46 UTC, gas1cent commented on solidity/test/integration/IntegrationBase.sol
> +    address[] memory authorizedCallers = new address[](1);
The linter is complaining on this line, let's add underscore to the variable:
```suggestion
    address[] memory _authorizedCallers = new address[](1);
```

2024-09-19 15:46 UTC, gas1cent commented on solidity/scripts/Deploy.sol
> +    bondEscalationAccounting = new BondEscalationAccounting(oracle, authorizedCallers);
Just a note here that we don't have any integration tests for the `BondEscalationResolutionModule`, only for the dispute one. Hence we're not adding it to the list of authorized callers.

2024-09-19 17:13 UTC, 0xJabberwock commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +    vm.assume(_amount < type(uint256).max);
Why `assume` here?

2024-09-19 17:15 UTC, 0xJabberwock commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +    vm.assume(_amount > 0);
Why `assume` here?

2024-09-19 17:17 UTC, 0xJabberwock commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +    _amountPerPledger = bound(_amountPerPledger, 1, type(uint256).max / _numOfWinningPledgers);
Why `bound` here?

2024-09-19 17:19 UTC, 0xJabberwock commented on solidity/contracts/extensions/BondEscalationAccounting.sol
> +  constructor(IOracle _oracle, address[] memory _authorizedCallers) AccountingExtension(_oracle) {
Why not `calldata`?

2024-09-19 17:20 UTC, 0xJabberwock commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +  ) BondEscalationAccounting(_oracle, _authorizedModules) {}
Should it be `authorizedCallers` or `authorizedModules`?

2024-09-19 18:52 UTC, xorsal commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +  ) BondEscalationAccounting(_oracle, _authorizedModules) {}
I chose 'callers' over 'modules' because the word 'module' in AccountingExtension, inherited by BondEscalationAccounting.

Also it's used by the Oracle:
```
    if (!authorizedCallers[msg.sender]) revert BondEscalationAccounting_UnauthorizedCaller();
    if (!ORACLE.allowedModule(_requestId, msg.sender)) revert AccountingExtension_UnauthorizedModule();
```

2024-09-19 18:59 UTC, xorsal commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> +    _amountPerPledger = bound(_amountPerPledger, 1, type(uint256).max / _numOfWinningPledgers);
You're right. It's not needed.

2024-09-19 19:02 UTC, xorsal commented on solidity/contracts/extensions/BondEscalationAccounting.sol
> +  constructor(IOracle _oracle, address[] memory _authorizedCallers) AccountingExtension(_oracle) {
You can't use `calldata` in constructors.

2024-09-19 20:59 UTC, 0xJabberwock commented on solidity/contracts/extensions/BondEscalationAccounting.sol
>      if (!ORACLE.allowedModule(_requestId, msg.sender)) revert AccountingExtension_UnauthorizedModule();
What do you think about including an `onlyAuthorizedCaller` modifier?

2024-09-20 13:03 UTC, xorsal commented on solidity/test/unit/modules/dispute/BondEscalationAccounting.t.sol
> -    vm.prank(unauthorizedCaller);
I changed_ `vm.prank` to `vm.startPrank` here because I was testing something but it doesn't hurt tbh

2024-09-20 15:26 UTC, 0xJabberwock commented on solidity/test/integration/BondEscalation.t.sol
> +    vm.expectRevert(IBondEscalationAccounting.BondEscalationAccounting_UnauthorizedCaller.selector);
I think the reversion should still be expected even when the attacker is an authorized caller.

2024-09-23 13:23 UTC, xorsal commented on solidity/test/integration/BondEscalation.t.sol
> +    vm.expectRevert(IBondEscalationAccounting.BondEscalationAccounting_UnauthorizedCaller.selector);
Good point.
What do you think about mocking authorizedCallers immediately after the line you selected, something like this:

```
    stdstore
      .target(address(_bondEscalationAccounting))
      .sig('authorizedCallers(address)')
      .with_key(_attacker)
      .checked_write(true);

    vm.expectRevert(ValidatorLib.ValidatorLib_InvalidDisputeBody.selector);
    _bondEscalationAccounting.releasePledge(mockRequest, mockDispute, _attacker, usdc, _pledgeSize * 4);
```

2024-09-24 13:54 UTC, xorsal commented on solidity/test/integration/BondEscalation.t.sol
> +    vm.expectRevert(IBondEscalationAccounting.BondEscalationAccounting_UnauthorizedCaller.selector);
Perfect 👌
Yes, I thought about that but redeploying the `BondEscalationAccounting` is somewhat cumbersome because integration tests rely on common variables like `mockRequest`.

2024-09-24 15:10 UTC, 0xJabberwock requested changes

2024-09-24 15:10 UTC, 0xJabberwock commented on solidity/test/integration/BondEscalation.t.sol
>      _deposit(_bondEscalationAccounting, proposer, usdc, _pledgeSize);
I think the whole dispute escalation flow should be replicated in `test_authorizedAttackerAllowedModules`, as these tests are meant to simulate a specific attack which was once possible.

2024-09-24 15:10 UTC, 0xJabberwock commented on solidity/test/integration/BondEscalation.t.sol
>      _bondEscalationAccounting.approveModule(mockRequest.requestModule);
The same as above for this transaction.

2024-09-24 15:48 UTC, xorsal commented on solidity/test/integration/BondEscalation.t.sol
>      _deposit(_bondEscalationAccounting, proposer, usdc, _pledgeSize);
I think this further escalation is only meant to exemplify a particular scenario (a request/dispute gathers tokens from multiple parties/sources) so it won't change the final result (revert when the attacker tries to finalize the attack) but I can add it to replicate the exact same scenario in `attackerAllowedModules`.

2024-09-24 16:55 UTC, 0xJabberwock commented on solidity/test/integration/BondEscalation.t.sol
>      _deposit(_bondEscalationAccounting, proposer, usdc, _pledgeSize);
I think the purpose of these test cases in particular should be to be anti-regressive with a specific bug, hence why I wouldn't disesteem the featured scenario in any of them. However, we can invoke its creator's opinion: @0xShaito.

2024-09-25 01:37 UTC, xorsal commented on solidity/test/integration/BondEscalation.t.sol
>      _deposit(_bondEscalationAccounting, proposer, usdc, _pledgeSize);
Anyway, I agree with your reasoning. I'll revert that commit and redo it.

2024-09-25 03:56 UTC, 0xJabberwock approved these changes

2024-09-25 09:05 UTC, merged