feat: non reverting callback modules
defi-wonderland/prophet-modules pull request #65
Opened 2024-10-08 11:40 UTC by xorsal

# 🤖 Linear

Closes OPO-657

2024-10-08 12:11 UTC, 0xShaito commented on solidity/test/mocks/MockCallback.sol
> +  function prophetCallback(bytes calldata /* _callData */ ) external pure returns (bytes memory /* _callResponse */ ) {
Lint

2024-10-13 20:39 UTC, ashitakah requested changes

2024-10-13 20:39 UTC, ashitakah commented on solidity/contracts/modules/finality/CallbackModule.sol
> +    _params.target.call(abi.encodeCall(IProphetCallback.prophetCallback, (_params.data)));
Should we check that target has bytecode? In order to avoid some problems or doesnt matter for us

2024-10-13 20:39 UTC, ashitakah commented on solidity/contracts/modules/finality/MultipleCallbacksModule.sol
> +      _params.targets[_i].call(abi.encodeCall(IProphetCallback.prophetCallback, (_params.data[_i])));
same here

2024-10-13 20:39 UTC, ashitakah commented on solidity/test/integration/CallbackModule.t.sol
> +    _deposit(_accountingExtension, requester, usdc, _expectedReward);
as the request and the response is always the same, you can move it to setup and you dont need to duplicate it

2024-10-13 20:39 UTC, ashitakah commented on solidity/test/integration/CallbackModule.t.sol
> +    vm.prank(proposer);
also startPrank yo avoid to have 2 lines and the same for the requester

2024-10-13 20:39 UTC, ashitakah commented on solidity/test/integration/MultipleCallbacksModule.t.sol
> +    address[] memory _targets = new address[](_length);
imo, I dont like to hace fuzzing values in the integrations. Set a data and a length also, for the "for loop" you can create an internal function something like:

```
function  _createDataCallback(bytes memory _data) internal  returns (bytes[] memory _datas) {
     _datas = new bytes[](_length);
    for (uint256 _i; _i < _length; _i++) {
      _targets[_i] = address(_callback);
      _datas[_i] = _data;
    }
```

2024-10-13 20:39 UTC, ashitakah commented on solidity/test/integration/MultipleCallbacksModule.t.sol
> +    //
same here with everything duplicate

2024-10-14 12:04 UTC, xorsal commented on solidity/contracts/modules/finality/MultipleCallbacksModule.sol
> +      _params.targets[_i].call(abi.encodeCall(IProphetCallback.prophetCallback, (_params.data[_i])));
`MultipleCallbacksModule::validateParameters` also checks for all targets bytecode

2024-10-14 12:05 UTC, xorsal commented on solidity/test/integration/MultipleCallbacksModule.t.sol
> +    address[] memory _targets = new address[](_length);
I agree. I'll change it :)

2024-10-14 18:10 UTC, ashitakah commented on solidity/contracts/modules/finality/CallbackModule.sol
> +    _params.target.call(abi.encodeCall(IProphetCallback.prophetCallback, (_params.data)));
👍

2024-10-14 18:11 UTC, ashitakah approved these changes
🔥

2024-10-15 14:18 UTC, 0xShaito approved these changes

2024-10-15 14:18 UTC, merged