test: request modules integration tests
defi-wonderland/prophet-modules pull request #66
Opened 2024-10-09 12:59 UTC by xorsal

# 🤖 Linear

Closes OPO-658

2024-10-13 20:47 UTC, ashitakah requested changes

2024-10-13 20:47 UTC, ashitakah commented on solidity/test/integration/ContractCallRequest.t.sol
> +  function test_createRequest_finalizeEmptyResponse(bytes4 _selector, bytes calldata _data) public {
From line 30 to 47 could be move it to the setup

2024-10-13 20:47 UTC, ashitakah commented on solidity/test/integration/ContractCallRequest.t.sol
> +  function test_createRequest_finalizeEmptyResponse(bytes4 _selector, bytes calldata _data) public {
also as the previous pr, if I were me I would delete the params and create a selector and a data for the test

2024-10-13 20:47 UTC, ashitakah commented on solidity/test/integration/ContractCallRequest.t.sol
> +contract Integration_ContractCallRequest is IntegrationBase {
Also probably when you finalize the request , in the oracle the status will change, would be awesome to have asserts for this status, and expectCall to check that pay al release have been called with the correct params.

2024-10-13 20:47 UTC, ashitakah commented on solidity/test/integration/HttpRequest.t.sol
> +contract Integration_HttpRequest is IntegrationBase {
similar comments that I put in the other test

2024-10-15 14:19 UTC, 0xShaito approved these changes

2024-10-15 14:19 UTC, merged