Feat/bond escalation tests
defi-wonderland/prophet-modules pull request #67
Opened 2024-10-13 20:57 UTC by ashitakah

# 🤖 Linear

Closes OPO-653

2024-10-14 11:21 UTC, xorsal requested changes
Looks good!
When you merge dev the usage of timestamp/expected deadlines will break because of #64

2024-10-14 18:07 UTC, ashitakah commented on solidity/test/integration/EscalateDispute.t.sol
> +    _mineBlocks(_blocksDeadline + 1);
👍

2024-10-14 18:07 UTC, ashitakah commented on solidity/test/integration/EscalateDispute.t.sol
> +    vm.warp(block.timestamp - (_blocksDeadline + _tyingBuffer + 1) * BLOCK_TIME);
👍

2024-10-14 18:07 UTC, ashitakah commented on solidity/test/integration/EscalateDispute.t.sol
> +    _mineBlocks(_tyingBuffer);
👍

2024-10-14 18:07 UTC, ashitakah commented on solidity/test/integration/EscalateDispute.t.sol
> +    _mineBlocks(_expectedDeadline + 1);
👍

2024-10-15 14:14 UTC, xorsal requested changes
I think it's almost there. There are couple errors in how `vm.warp` is used. I left a some comments, but there a few identical errors throughout the file.

2024-10-15 14:14 UTC, xorsal commented on solidity/test/integration/EscalateDispute.t.sol
> +    // Roll back the blocks because we need to simulate the custom error "break tie during tying buffer" and "bond escalation over"
_Roll back the timestamp_

2024-10-15 14:14 UTC, xorsal commented on solidity/test/integration/EscalateDispute.t.sol
> +    vm.warp(block.timestamp + _disputeCreatedAt + _expectedDeadline + 1);
`disputeCreatedAt` is a value that comes from the Oracle and it's should be a timestamp, so doing `block.timestamp + _disputeCreatedAt` is probably wrong.

2024-10-15 14:14 UTC, xorsal commented on solidity/test/integration/EscalateDispute.t.sol
> +    vm.warp(block.timestamp + _disputeCreatedAt + _blocksDeadline + 1);
Idem above.

2024-10-15 14:14 UTC, xorsal commented on solidity/test/integration/EscalateDispute.t.sol
> +    vm.warp(block.timestamp - (_disputeCreatedAt + _blocksDeadline + 1));
instead you could rollback the timestamp doing `vm.warp(_disputeCreatedAt)`

2024-10-15 15:46 UTC, 0xShaito commented on solidity/test/integration/EscalateDispute.t.sol
> +    vm.warp(block.timestamp + _disputeCreatedAt + _expectedDeadline + 1);
Because we never warp before in this test, the creation of the dispute is in the same block as timestamp (now). I think that it would be good to advance some time after creation of dispute and use the creation time in the oracle just to do it more in line with reality

2024-10-15 15:47 UTC, 0xShaito commented on solidity/test/integration/EscalateDispute.t.sol
> +    vm.warp(block.timestamp + _expectedDeadline + _tyingBuffer + 1);
Lets change all block.timestamp to the dispute creation time

2024-10-17 15:31 UTC, ashitakah commented on solidity/test/integration/EscalateDispute.t.sol
> +    // Roll back the blocks because we need to simulate the custom error "break tie during tying buffer" and "bond escalation over"
👍

2024-10-17 15:36 UTC, ashitakah commented on solidity/test/integration/EscalateDispute.t.sol
> +    vm.warp(block.timestamp - (_disputeCreatedAt + _blocksDeadline + 1));
Its true, however as I know that this logic is more complex I decided to do like this in order to clarify that we are doing something "triky" and is not the natural flow

2024-10-21 13:42 UTC, xorsal commented on solidity/test/integration/EscalateDispute.t.sol
> +    vm.roll(1 days);
Just noticed this one. It's confusing to use `vm.roll` with a time constant

2024-10-23 11:22 UTC, 0xShaito approved these changes

2024-10-24 09:39 UTC, xorsal approved these changes

2024-10-24 09:43 UTC, merged