fix: bonded response release unutilized response
defi-wonderland/prophet-modules pull request #71
Opened 2024-10-23 07:49 UTC by 0xShaito

# 🤖 Linear

Closes OPO-665

2024-11-06 04:32 UTC, 0xJabberwock requested changes

2024-11-06 04:32 UTC, 0xJabberwock commented on solidity/test/integration/Finalization.t.sol
> +    oracle.finalize(mockRequest, _disputedResponse);
In contradiction with the code comment, I think `_disputedResponse` is not empty.

2024-11-06 04:32 UTC, 0xJabberwock commented on solidity/test/integration/Finalization.t.sol
> +  function test_releaseUnutilizedResponse(bytes calldata _calldata) public {
At least two tests should be featured with regards to the successful execution of `BondedResponseModule::releaseUnutilizedResponse`:
- one in which the request has finalized with response, and
- one in which the request has finalized without response.
 
It would be cool to test within them whether the `BondedResponseModule_InvalidReleaseParameters` errors are thrown when appropriate.

2024-11-06 04:52 UTC, 0xJabberwock commented on solidity/test/integration/Finalization.t.sol
> +    _proposeResponse();
The bug could be replicated with only one response, so there's no need to propose again.

2024-11-13 08:26 UTC, gas1cent commented on solidity/test/integration/Finalization.t.sol
> +    _proposeResponse();
2db24481841036560d5f0f09f4f41b35cb23420b 🫡

2024-11-13 09:29 UTC, gas1cent commented
Waiting for #78 to fix the CI.

2024-11-13 15:22 UTC, 0xJabberwock approved these changes

2024-11-13 15:32 UTC, merged