wip: access control
defi-wonderland/prophet-modules pull request #74
Opened 2024-10-23 20:41 UTC by xorsal

# 🤖 Linear

Closes OPO-XXX

2024-10-24 08:03 UTC, 0xShaito commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +import '../../utils/Typehash.sol';
Lint

2024-10-24 08:04 UTC, 0xShaito commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +contract BondEscalationModule is AccessController, Module, IBondEscalationModule {
Should be accessControllerModule. Lets not use the AccessController in modules

2024-10-24 08:04 UTC, 0xShaito commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +    onlyOracle
No access control in onlyOracle functions

2024-10-24 08:05 UTC, 0xShaito commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +contract BondEscalationModule is AccessController, Module, IBondEscalationModule {
Remember that the module one also validates that the access control module was previously approved by the user

2024-10-24 08:06 UTC, 0xShaito commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +    // review: access control?
If no msg.sender used then no

2024-10-24 08:31 UTC, 0xShaito commented on solidity/contracts/modules/resolution/BondEscalationResolutionModule.sol
> +        uint256 _pledgerBalanceFor = pledgesForDispute[_disputeId][msg.sender];
msg.sender 😨

2024-10-24 08:32 UTC, 0xShaito commented on solidity/contracts/modules/resolution/ERC20ResolutionModule.sol
> +    public // review: why not external?
If we can change it to external lets do it

2024-10-24 08:33 UTC, 0xShaito commented on solidity/contracts/modules/resolution/ERC20ResolutionModule.sol
> +      ORACLE.updateDisputeStatus(_request, _response, _dispute, IOracle.DisputeStatus.Won, _defaultAccessControl());
updateDisputeStatus should remove the access control

2024-10-24 08:33 UTC, 0xShaito commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +    hasAccess(_request.accessControlModule, _COMMIT_VOTE_TYPEHASH, abi.encode(_request, _dispute), _accessControl)
Parameter _commitment

2024-10-24 08:33 UTC, 0xShaito commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +    hasAccess(_request.accessControlModule, _REVEAL_VOTE_TYPEHASH, abi.encode(_request, _dispute), _accessControl)
Aparameter salt and number of votes

2024-10-24 08:35 UTC, 0xShaito commented on solidity/contracts/modules/response/BondedResponseModule.sol
> +  function releaseUnutilizedResponse(
No msg.sender used?

2024-10-24 08:36 UTC, 0xShaito commented on solidity/test/mocks/MockArbitrator.sol
> +    IAccessController.AccessControl memory AccessControl
Linter

2024-10-24 08:40 UTC, 0xShaito commented on solidity/contracts/modules/dispute/RootVerificationModule.sol
> +    ORACLE.updateDisputeStatus(_request, _response, _dispute, _status, _defaultAccessControl());
The _defaultAccessControl() function is a great idea! 

Let's have it defined as an immutable in the AccessControllerModule.

SELF_ACCESS_CONTROL = AccessControl(user: address(this), data: bytes(0)) 

Or something like this

2024-10-24 08:40 UTC, 0xShaito requested changes
Great draft. Some small comments and we should have it ready pretty soon

2024-10-24 10:48 UTC, xorsal commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +    onlyOracle
I deleted some of the outdated `review` comments, but looks like I missed a few of them.

2024-10-24 10:52 UTC, xorsal commented on solidity/contracts/modules/resolution/BondEscalationResolutionModule.sol
> +        uint256 _pledgerBalanceFor = pledgesForDispute[_disputeId][msg.sender];
I had to leave it like this due to the _too many local variables_ error.
I believe I didn't use `_accessControl.user` again here after the change in line 168 of this file (`uint256 _reward` moved inside curly brackets). I'll try again and follow up.

2024-10-24 10:54 UTC, xorsal commented on solidity/contracts/modules/resolution/PrivateERC20ResolutionModule.sol
> +    hasAccess(_request.accessControlModule, _COMMIT_VOTE_TYPEHASH, abi.encode(_request, _dispute), _accessControl)
Thanks.
I'll review all instances of `hasAccess` to ensure it passes all the corresponding parameters.

2024-10-24 13:06 UTC, xorsal commented on solidity/contracts/modules/dispute/RootVerificationModule.sol
> +    ORACLE.updateDisputeStatus(_request, _response, _dispute, _status, _defaultAccessControl());
Making it immutable is even better!

2024-10-31 15:59 UTC, xorsal commented
There are only two unit tests for the usage of `hasAccess` in `BondEscalationModule::pledgeForDispute`:
[137d27e](https://github.com/defi-wonderland/prophet-modules/pull/74/commits/137d27e89c253a5d992d9a233b5df1cfabe223ba)
[124764a](https://github.com/defi-wonderland/prophet-modules/pull/74/commits/124764ac79ef63bac2ea9b6f4fa4f44a40c99772)

I can add one for each function that uses it to maintain the coverage :)

2024-10-31 16:00 UTC, xorsal commented on solidity/contracts/modules/resolution/BondEscalationResolutionModule.sol
> +        uint256 _pledgerBalanceFor = pledgesForDispute[_disputeId][msg.sender];
fixed in [eae4ea1](https://github.com/defi-wonderland/prophet-modules/pull/74/commits/eae4ea18a5a654fecde94722e5cfe3baafbfe6cc) and [618cc36](https://github.com/defi-wonderland/prophet-modules/pull/74/commits/618cc36999e534ce68a011977319ec9c10522eba)

2024-10-31 21:45 UTC, ashitakah requested changes
Well done! 🔥

2024-10-31 21:45 UTC, ashitakah commented on solidity/contracts/modules/accessControl/AccessControllerModule.sol
> +  function _defaultAccessControl() internal view returns (AccessControl memory _accessControl) {
I like the idea, but Im nor sure if we should build the AccessControl struct in every function. Maybe, we need to pass some data. Not now, but maybe with another access control module

2024-10-31 21:45 UTC, ashitakah commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +      ORACLE.escalateDispute(_request, _response, _dispute, _defaultAccessControl());
I.E. here maybe we should add acessControl in the function params and pass it to escalate dispute. Even if the user will be the module maybe the data is not. But im not sure tbh

2024-10-31 21:45 UTC, ashitakah commented on solidity/test/unit/modules/dispute/CircuitResolverModule.t.sol
> +      // abi.encodeWithSelector(
commented?

2024-10-31 21:45 UTC, ashitakah commented on solidity/test/unit/modules/dispute/CircuitResolverModule.t.sol
> +      // abi.encodeWithSelector(
same here

2024-10-31 21:45 UTC, ashitakah commented on solidity/test/unit/modules/dispute/CircuitResolverModule.t.sol
> +      // abi.encodeWithSelector(
+1

2024-11-02 13:10 UTC, xorsal commented
By the end of the developement I learned about `vm.readCallers()` from which you can obtain the current pranked address. I think that in most cases I could use `_createAccessControl()` (no address specified) and it should work because I'm always using the trivial access control case (`msg.sender` equal to AC.user`).

I think the only pending thing is adding access control usage in resolveDispute, but this change depends from `prophet-core` PR, after this change is added there adding it here should be fairly quick.

2024-11-04 18:15 UTC, 0xJabberwock requested changes

2024-11-04 18:15 UTC, 0xJabberwock commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +      ORACLE.escalateDispute(_request, _response, _dispute, _defaultAccessControl());
Valid concern. An option could be to default the `AccessControl` struct instantiation to `DefaultAccessControlModule`, passing to it a pertinent typehash argument.

2024-11-04 18:28 UTC, 0xJabberwock commented on solidity/contracts/modules/response/BondedResponseModule.sol
>      bool _isModule = ORACLE.allowedModule(_response.requestId, _finalizer);
👀

2024-11-04 18:34 UTC, xorsal commented on solidity/contracts/modules/response/BondedResponseModule.sol
>      bool _isModule = ORACLE.allowedModule(_response.requestId, _finalizer);
I need to remove all the `// review` comments.

2024-11-04 18:40 UTC, xorsal commented on solidity/contracts/modules/resolution/BondEscalationResolutionModule.sol
> +      revert BondEscalationResolutionModule_PledgingPhaseOver();
I had to change this to avoid stack too deep error.
I'll remove the commented line.

2024-11-04 20:29 UTC, xorsal commented on solidity/contracts/modules/accessControl/AccessControllerModule.sol
> +  constructor(IOracle _oracle) Module(_oracle) {}
>As it is now, it seems that every module contains in itself an unshared abstract access control module,

What makes you think it is unshared? Each request sets the address for its access control module, which might be shared or unique between different requests. However, for the same request, the access control module remains the same across all modules and the Oracle.

>which, by the way, doesn't even include the aforementioned function.

Would this be fixed if I declared something like `function hasAccess(bytes calldata _accessControlParameters) external virtual returns(bool _hasAccess)`?

2024-11-04 21:52 UTC, 0xJabberwock commented on solidity/contracts/modules/accessControl/AccessControllerModule.sol
> +  constructor(IOracle _oracle) Module(_oracle) {}
Hmm, I think some confusion is arising for me in relation with the system's separation of concerns.

In my view, there should be an `OracleAccessController`, to be used solely by the `Oracle`, and perhaps a `ModuleAccessController`, to be used by modules which need to control access to certain functions (e.g., those which pledge). I'd expect the latter to delegate its controller checks to the former, effectively producing a call to `Oracle` in order to ascertain `isAccessControlApproved` and then to call to an access control module in question.

Following the above, the access control module in question should have a separate implementation, for which I proposed a general `DefaultAccessControlModule`.

In line with my declared view, I leave some questions:
- Is the current `AccessControllerModule` meant to be the `ModuleAccessController`? If so, why does it inherit from `AccessController` (i.e., `OracleAccessController`) and why does it inherit from `Module`?
- Is the current `AccessControllerModule ` meant to be an access control module? If so, why does it inherit from `AccessController` (i.e., `OracleAccessController `) and why doesn't it define `hasAccess()`?

2024-11-05 02:45 UTC, xorsal commented on solidity/contracts/modules/accessControl/AccessControllerModule.sol
> +  constructor(IOracle _oracle) Module(_oracle) {}
I see the AccessController as the common logic for authenticating third parties acting on behalf of a user, and I'd expect this logic to be the same in both the Oracle and the modules. This is why the module implementations extend (through `AccessControllerModule`) the `AccessController`.

I agree that it should call the Oracle to verify that the user, on whose behalf the caller is acting, has actually authorized the use of a given access control module address, but this can also be achieved by adding another yet another modifier that makes the appropiate external call to the Oracle.

>Is the current AccessControllerModule meant to be an access control module? If so, why does it inherit from AccessController (i.e., OracleAccessController ) and why doesn't it define hasAccess()?

`AccessControllerModule` cannot be an access control module, mainly because it's an abstract contract. But more importantly, it's only used to extend the necessary logic to enable access control in a given module. Instead of extending both `Module` and `AccessController` separately I'm extending `AccessControllerModule`, which already extends both of them.

2024-11-05 05:40 UTC, 0xJabberwock commented on solidity/contracts/modules/accessControl/AccessControllerModule.sol
> +  constructor(IOracle _oracle) Module(_oracle) {}
> I see the AccessController as the common logic for authenticating third parties acting on behalf of a user, and I'd expect this logic to be the same in both the Oracle and the modules. This is why the module implementations extend (through `AccessControllerModule`) the `AccessController`.

I get your point. I wouldn't expect the logic in `AccessController` to be shared between the `Oracle` and the modules, particularly because I would include in it all the new functionality that it brings (such as the state variable `isAccessControlApproved` or its setter function). I had pointed this out to @ashitakah and he had initially agreed (https://github.com/defi-wonderland/prophet-core/pull/52#discussion_r1825944020), but his latest commit shows repentance (https://github.com/defi-wonderland/prophet-core/pull/52/commits/69e47b07963c8f1d49b6f2639f1407a67f5cf699). 🤷

> Instead of extending both `Module` and `AccessController` separately I'm extending `AccessControllerModule`, which already extends both of them.

Why would you extend from `Module`? I'd expect an access control module to do so, of course, but not an access controller, which might fit better in the category of module extensions. ([Source](https://dev.docs.prophet.tech/content/intro/framework.html#extensions))

2024-11-05 13:07 UTC, xorsal commented on solidity/contracts/modules/accessControl/AccessControllerModule.sol
> +  constructor(IOracle _oracle) Module(_oracle) {}
>Why would you extend from Module? I'd expect an access control module to do so, of course, but not an access controller, which might fit better in the category of module extensions. ([Source](https://dev.docs.prophet.tech/content/intro/framework.html#extensions))

Modules that need to use access control extends from `AccessControllERModule`, which is the one that extends both `Module` and `AccessController`.
`AccessControlModule` would also extend from `Module` but not from `AccessController` as it doesn’t need to perform the access control check itself. Instead it only enforces whatever rules/logic `function hasAccess(bytes)` implements for any caller, whether if it's the oracle or another module.

Initially I took an approach similar to what you're suggesting: [here](https://github.com/defi-wonderland/prophet-modules/pull/74/commits/522cb38cc4e9adcebe2f0ff19b2515c7736fec37#diff-90b5310733d1471814599ed4fa9f76ffe9a6d2a874903787fa446bd3929ec997R16), but we thought it was better easier to understand with the current implementation. Clearly it isn't the case

2024-11-05 19:53 UTC, 0xJabberwock commented on solidity/contracts/utils/Typehash.sol
> +  keccak256('pledgeForDispute(Request _request, Dispute _dispute,IAccessController.AccessControl _accessControl)');
Relevant discussion about making `Typehash` a contract: https://github.com/defi-wonderland/prophet-core/pull/52#discussion_r1828668308.

2024-11-07 19:02 UTC, xorsal commented on solidity/contracts/modules/dispute/BondEscalationModule.sol
> +  {
Fixed in #77

2024-11-10 20:35 UTC, gas1cent commented on solidity/contracts/modules/access/ModuleAccessController.sol
> +abstract contract ModuleAccessController is IModuleAccessController, CommonAccessController, Module {
What's the rationale for having this contract here and not in the core repo? A developer building a new module would appreciate the fact they only have to instal one package.

2024-11-10 21:48 UTC, 0xJabberwock commented on solidity/contracts/modules/access/ModuleAccessController.sol
> +abstract contract ModuleAccessController is IModuleAccessController, CommonAccessController, Module {
Noticed, discussed and agreed on in the accessory PR: https://github.com/defi-wonderland/prophet-modules/pull/77#discussion_r1833214375.

2024-11-11 18:03 UTC, xorsal commented on solidity/contracts/modules/access/ModuleAccessController.sol
> +abstract contract ModuleAccessController is IModuleAccessController, CommonAccessController, Module {
Tracked in OPT-530

2024-11-12 08:18 UTC, gas1cent commented on solidity/contracts/modules/response/BondedResponseModule.sol
>      bool _isModule = ORACLE.allowedModule(_response.requestId, _finalizer);
OPT-531

2024-11-12 08:19 UTC, gas1cent commented on solidity/contracts/utils/Typehash.sol
> +  keccak256('pledgeForDispute(Request _request, Dispute _dispute,IAccessController.AccessControl _accessControl)');
Adjusted in https://github.com/defi-wonderland/prophet-modules/pull/74/commits/15061dbfaad8754105ac718daff37d7125baa1a8

2024-11-12 08:19 UTC, gas1cent commented on solidity/interfaces/IArbitrator.sol
> +    IAccessController.AccessControl memory _accessControl
Removed the access control parameter from `IArbitrator` and modules inheriting that interface: https://github.com/defi-wonderland/prophet-modules/pull/74/commits/78dd38de6551b35be62edecd769d7e3ab803480b

2024-11-12 14:25 UTC, 0xJabberwock commented on solidity/contracts/modules/access/ModuleAccessController.sol
> +    _hasAccess(_accessModule, _typehash, _params, _accessControl);
The `hasAccess` checks in `ModuleAccessController` should be updated similarly to those of `hasAccess` in `OracleAccessController`.

2024-11-12 15:38 UTC, 0xJabberwock approved these changes

2024-11-12 15:38 UTC, 0xJabberwock commented on report.md
`report.md` has just been introduced—did you mean to push this file or should it be placed in `.gitignore`?

2024-11-12 15:39 UTC, gas1cent commented on report.md
Removed ser, good catch.

2024-11-12 15:40 UTC, 0xJabberwock approved these changes

2024-11-12 15:46 UTC, merged