feat: access module
defi-wonderland/prophet-modules pull request #77
Opened 2024-11-06 17:46 UTC by xorsal

# 🤖 Linear

Closes OPO-XXX

2024-11-07 19:00 UTC, ashitakah requested changes

2024-11-07 19:00 UTC, ashitakah commented on solidity/contracts/modules/accessControl/ModuleAccessController.sol
> +      bool _isApproved = ORACLE.isAccessModuleApproved(_accessControl.user, _accessModule);
why create a variable instead of put the call inside the if

2024-11-07 20:04 UTC, 0xJabberwock commented on solidity/contracts/modules/accessControl/ModuleAccessController.sol
>      _accessControl = _defaultAccessControl(bytes(''));
Reminder for the future: `_defaultAccessControl()` shall get the default `AccessControl` struct by calling `IAccessModule.defaultAccessControl`.

2024-11-07 20:14 UTC, xorsal commented on solidity/contracts/modules/accessControl/ModuleAccessController.sol
>      _accessControl = _defaultAccessControl(bytes(''));
Created a task to track this because it's a nice improvement: OPT-520
Out of the scope for the EBO integration

2024-11-07 20:15 UTC, xorsal commented on solidity/contracts/modules/dispute/CircuitResolverModule.sol
> +import {ModuleAccessController} from '../accessControl/ModuleAccessController.sol';
Yes, I have an unpushed commit with this change.

2024-11-07 20:16 UTC, xorsal commented on solidity/contracts/modules/dispute/CircuitResolverModule.sol
> +contract CircuitResolverModule is ModuleAccessController, ICircuitResolverModule {
I agree. We can safely remove the usage of ModuleAccessController. Thank you for the reminder, I did it on `BondedResponseModule` but completely forgot to also apply the change in the other modules.

2024-11-07 20:20 UTC, xorsal commented on solidity/contracts/modules/accessControl/ModuleAccessController.sol
> +      bool _isApproved = ORACLE.isAccessModuleApproved(_accessControl.user, _accessModule);
Nice! Applying change.

2024-11-07 20:38 UTC, xorsal commented on solidity/contracts/modules/accessControl/ModuleAccessController.sol
> +      if (!_isApproved) revert AccessController_NoAccess();
I guess you're right. I don't like having two different errors for the same type of revert (i.e., _user has not approved the given access module_). Although in this one it's not literally the same as in the Oracle because it's caused as a result of an external call to the Oracle.

2024-11-08 09:42 UTC, xorsal commented on solidity/contracts/modules/dispute/CircuitResolverModule.sol
> +contract CircuitResolverModule is ModuleAccessController, ICircuitResolverModule {
Ahh, I didn't forget about them. They use `_defaultAccessControll()`.
CircuitResolver and RootVerification modules calls `IOracle::proposeResponse` and `IOracle.finalize`, which are access-controlled. Arbitrator calls to `IOracle::resolve`, access-controlled as well.

2024-11-08 11:47 UTC, xorsal commented on solidity/contracts/modules/accessControl/ModuleAccessController.sol
> +abstract contract ModuleAccessController is CommonAccessController, Module {
I feel the same about `ModuleAccessController` inheriting from `Module`. The need to extend `Module` comes from the necessity of accessing the `ORACLE` immutable variable, which is actually define in `Validator`, from which `Module` extends.

I like the suggestion, but I'd add it in a future, smaller PR to unblock the current chain of PRs.

2024-11-08 14:41 UTC, 0xJabberwock approved these changes

2024-11-08 14:41 UTC, 0xJabberwock commented on solidity/contracts/modules/access/ModuleAccessController.sol
> +      revert ModuleAccessController_AccessModuleNotApproved();
I feel it simpler to have just one `hasAccess` modifier which checks for approval and access (as in here), instead of separated `isApproved` and `hasAccess` (as in `OracleAccessController`).

2024-11-10 20:32 UTC, gas1cent commented on solidity/contracts/modules/access/ModuleAccessController.sol
> +      revert ModuleAccessController_AccessModuleNotApproved();
> I feel it simpler to have just one hasAccess modifier which checks for approval and access (as in here), instead of separated isApproved and hasAccess (as in OracleAccessController).

Great suggestion, done in the core PR.

> By the way, I think _hasAccess should be executed only when msg.sender != _accessControl.user.

Will be done separately.

2024-11-10 20:32 UTC, merged