chore: move unused modules
defi-wonderland/prophet-modules pull request #79
Opened 2024-11-13 15:24 UTC by xorsal

# 🤖 Linear

Closes OPT-395

2024-11-13 15:38 UTC, 0xJabberwock requested changes

2024-11-13 15:38 UTC, 0xJabberwock commented on solidity/contracts/examples/README.md
> +The contracts included in the examples folder have not been thoroughly tested nor audited. This are meant to use as example or inspiration for new modules. Do not use them in a production environment
```suggestion
The contracts included in the examples folder have not been thoroughly tested nor audited. These are meant to be used as examples or inspiration for new modules. Do not use them in a production environment.
```

Or copy and paste the caution message used in the docs.

2024-11-13 16:58 UTC, 0xJabberwock approved these changes

2024-11-14 15:42 UTC, 0xJabberwock approved these changes

2024-11-14 15:56 UTC, xorsal commented
Lets not merge this one until I gather a bit more info about the problem described in OPT-542.

2024-11-17 12:22 UTC, merged